In [3]:
import numpy as np

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x = np.array([1,2,3])

In [9]:
x.size


3

In [10]:
x.shape

(3,)

In [11]:
x.ndim

1

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
arra = np.arange (10)

In [14]:
arra


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arra2d = np.array([[1,2], [3,4]])

In [20]:
arra2d


array([[1, 2],
       [3, 4]])

In [21]:
arra2d.shape

(2, 2)

In [22]:
arra2d = np.arange(20).reshape(1,20)

In [23]:
arra2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [24]:
arra2d = np.arange(20).reshape(1,20)

In [25]:
arra2d = np.arange(20).reshape(1,20)
print(arra2d)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


In [26]:
arra2d = np.arange(20).reshape(20,1)
print(arra2d)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [28]:
arra2d = np.arange(20).reshape(4, 5)
print(arra2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [29]:
a = np.array(10)

In [30]:
a


array(10)

In [32]:
a.ndim

0

In [34]:
arr = np.array([10])

In [35]:
arr

array([10])

In [37]:
arr.ndim

1

In [38]:
arr = np.array([[10]])

In [39]:
arr

array([[10]])

In [40]:
arr3d = np.arange(64).reshape(4,4,4)

In [41]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [42]:
arr3d[1, 2, 2]


26

In [43]:
arr3d * 0

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [44]:
a = a.arange([30])

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [45]:
a = a.arange(30)

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [46]:
a = np.arraye(a.arange([30]))

AttributeError: module 'numpy' has no attribute 'arraye'

In [47]:
a = np.arange([30])

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [48]:
a = np.arange(30)